---
engines:
  duplication:
    enabled: false
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
      - typescript
  eslint:
    enabled: true
    checks:
      wrap-iife:
        enabled: false
      no-void:
        enabled: false
      no-proto:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
  - "**.ts"
exclude_paths:
- test/
- lib/
